# Generated by Django 5.2.2 on 2025-06-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='publish_date', verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], max_length=20)),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('publish_date', models.DateField(verbose_name='Дата публикации')),
                ('categories', models.ManyToManyField(to='myproject.category', verbose_name='Категории')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подзадачи')),
                ('description', models.TextField(verbose_name='Описание подзадачи')),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], max_length=20)),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='myproject.task', verbose_name='Основная задача')),
            ],
        ),
    ]
